# Battlestar-AI makefile
# http://code.google.com/p/battlestar-ai/

# Include source and header files:
SRC = battleship.cpp
HDR = abc123.h scs12.h

# Build all:
all: $(SRC) $(HDR)
	g++ -Wall -Wextra $(SRC) -o battlestar-ai

# Clean all:
clean:
	rm -f *.o